Repository kyma-incubator/ord-service, pull requests merged in 2021-12, with the labels that each got.

#48 Adopt storage redesing
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/TombstoneEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
Labels: size/M, lgtm

#49 Update SB version
  components/ord-service/pom.xml
  components/ord-service/src/main/resources/application.yml
Labels: :wave: request review, size/XS, lgtm

#50 Introduce defaultBundle for APIs/Events
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleReference.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ConsumptionBundleReference.java
Labels: size/XS, lgtm

#51 Respect dirty flag on schema version in readiness probe
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/health/ReadinessHealthIndicator.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SchemaEntity.java
Labels: bug, :wave: request review, size/S, lgtm
