Repository kyma-incubator/ord-service, pull requests merged in 2021-05, with the labels that each got.

#23 Manage used connections with CP settings
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/config/EclipseLinkJpaConfiguration.java
  components/ord-service/src/main/resources/application.yml
Labels: :wave: request review, lgtm, size/XS

#21 Adapting ORD RC2
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ConsumptionBundleReference.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
Labels: lgtm, size/M

#25 Adapt rc3 changes
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ExtensibleEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
Labels: :wave: request review, lgtm, size/S

#27 Fix typo
  README.md
  components/ord-service/pom.xml
Labels: lgtm, size/XS

#28 Return proper media type for specifications
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/SpecificationsController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SpecificationEntity.java
Labels: :wave: request review, lgtm, size/M
