Repository kyma-incubator/ord-service, pull requests merged in 2021-08, with the labels that each got.

#33 Enable formation filtering
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SpecificationEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
Labels: :wave: request review, size/S, lgtm

#34 add readiness indicator
  components/ord-service/run.sh
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/health/ReadinessHealthIndicator.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SchemaRepository.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SchemaEntity.java
  components/ord-service/src/main/resources/application.yml
Labels: :wave: request review, size/M, lgtm

#35 Use baseURL from request context for spec URL instead of env
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/converter/UrlConverter.java
  components/ord-service/src/main/resources/application.yml
  components/ord-service/src/test/java/com/sap/cloud/cmp/ord/service/storage/model/converter/UrlConverterTest.java
  components/ord-service/src/test/resources/application.yml
Labels: :wave: request review, size/M, lgtm

#36 Update dependencies
  components/ord-service/pom.xml
Labels: :wave: request review, size/XS, lgtm

#37 Bump spring boot
  components/ord-service/pom.xml
Labels: size/XS, lgtm

#38 Fix extensible description
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/filter/aggregator/JsonArrayElementsAggregator.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ExtensibleEntity.java
Labels: :wave: request review, size/XS, lgtm
