Repository kyma-incubator/ord-service, pull requests merged in 2022-01, with the labels that each got.

#53 Add documentation labels
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
Labels: size/S, lgtm

#55 Bump JRE image
  components/ord-service/Dockerfile
Labels: size/XS, lgtm

#56 ORD Global Registry for global products / vendors
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
Labels: :wave: request review, size/XS, lgtm

#58 Replace SpringFox with SpringDoc
  components/ord-service/pom.xml
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/config/SpringDocConfig.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/config/SpringFoxConfig.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/SpecificationsController.java
  components/ord-service/src/main/resources/application.yml
  components/ord-service/src/test/resources/application.yml
Labels: :wave: request review, lgtm, size/L
