Repository kyma-incubator/ord-service, pull requests merged in 2022-08, with the labels that each got.

#72 Tenancy on Embeddable entities & Joins Optimisation
  components/ord-service/pom.xml
  components/ord-service/scripts/install_dependencies.sh
Labels: :wave: request review, size/XS, lgtm

#74 Adjust embedded entities with new separated views
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/ChangelogAPIDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/ChangelogEventDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdApplication.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdBundle.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CountryAPIDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CountryEventDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CountryPackage.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabel.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelAPIDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelApplication.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelBundle.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelEventDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelPackage.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelVendor.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/IndustryAPIDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/IndustryEventDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/IndustryPackage.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityAPIDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityApplication.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityBundle.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityEventDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityPackage.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityVendor.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LineOfBusinessAPIDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LineOfBusinessEventDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LineOfBusinessPackage.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityAPIDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityBundle.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityEventDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityPackage.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagAPIDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagEventDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagPackage.java
Labels: :wave: request review, size/XXL, lgtm

#75 Bump docker image version
  components/ord-service/Dockerfile
  components/ord-service/pom.xml
Labels: size/XS, lgtm

#77 Adapt deploy-on-minikube for k3d
  scripts/generic_make_go.mk
Labels: size/S, lgtm

#78 Change tenant IDs from string to uuid
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/SpecificationsController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SpecRepository.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SpecificationEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/TombstoneEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
Labels: :wave: request review, size/M, lgtm
