Repository kyma-incubator/ord-service, pull requests merged in 2023-02, with the labels that each got.

#86 Bump base Docker images and dependencies
  components/ord-service/Dockerfile
  components/ord-service/pom.xml
Labels: :wave: request review, size/M, lgtm

#88 Adopt ORD 1.1.4
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
Labels: :wave: request review, lgtm

#87 Filter ORD Service response based on formations for SaaS application consumers
  .gitignore
  components/ord-service/.gitignore
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SelfRegisteredRuntimeRepository.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/TombstoneEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/VendorEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/Token.java
Labels: :wave: request review, lgtm, size/L
