Repository kyma-incubator/ord-service, pull requests merged in 2023-10, with the labels that each got.

#100 Adapt ORD from v1.5.0 to v1.5.3
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/TombstoneEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/HierarchyAPIDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/HierarchyEventDefinition.java
Labels: :wave: request review, size/M, lgtm

#101 Add OWNERS files
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
Labels: :wave: request review, size/M, lgtm

#102 Update dependencies
  components/ord-service/Dockerfile
  components/ord-service/pom.xml
Labels: :wave: request review, size/S, lgtm

#103 Adopt latest ORD specification - v1.4.0, v1.4.1 and v1.4.2
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/SpecificationsController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/filter/aggregator/JsonArrayElementsAggregator.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SpecRepository.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/CapabilityDefinition.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/CapabilityEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SpecificationEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdCapability.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelCapability.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityCapability.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityCapability.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagCapability.java
Labels: :wave: request review, lgtm, size/L

#104 Adopt ORD specification
  components/ord-service/pom.xml
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EntityTypeEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ProductEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/ChangelogEntityType.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdEntityType.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelEntityType.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EntityTypeProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EntityTypeSuccessor.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityEntityType.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityType.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagEntityType.java
Labels: :wave: request review, lgtm, size/L
