Repository kyma-incubator/ord-service, pull requests merged in 2023-11, with the labels that each got.

#106 Add IntegrationDependency and Aspect entities
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectAPIResource.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectEventResource.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/AspectEventResourceSubset.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EntityTypeEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/IntegrationDependencyEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/ResourceLink.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/AspectEventResourceSubset.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdIntegrationDependency.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelIntegrationDependency.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EventResourceLinkEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/IntegrationDependencySuccessor.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityIntegrationDependency.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityIntegrationDependency.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/RelatedIntegrationDependencies.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagIntegrationDependency.java
Labels: lgtm, size/XL

#105 Adopt ORD specification 1.6.3
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIModelSelector.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/CapabilityEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EntityTypeEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EntityTypeMappingEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EntityTypeTarget.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EntityTypeMappingAPIModelSelector.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/EntityTypeMappingEntityTypeTarget.java
Labels: :wave: request review, lgtm, size/L

#108 Fix missing top-level filter in the generated SQL where clause
  components/ord-service/pom.xml
Labels: size/XS, lgtm

#111 Adapt tenant claims
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/DestinationEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/Token.java
Labels: :wave: request review, size/S, lgtm

#112 Add tenant and formation id to capability
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/CapabilityEntity.java
Labels: size/S, lgtm
