Repository kyma-incubator/ord-service, pull requests merged in 2024-01, with the labels that each got.

#118 Filter formations by discovery consumers allowlist of the formation template
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SelfRegisteredRepository.java
Labels: :wave: request review, size/XS, lgtm, cla: yes

#117 Adopt ORD spec to v1.8.5
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/APIEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/DataProductEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/DataProductLink.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/EventEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/InputPort.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/OutputPort.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/PackageEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/ChangelogDataProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/CorrelationIdDataProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DataProductEntityTypes.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DataProductLinkEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DataProductSuccessor.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/DocumentationLabelDataProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/IndustryDataProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/InputPortsDataProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LabelEntityDataProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LineOfBusinessDataProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/LinkEntityDataProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/OutputPortsDataProduct.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/helperentities/TagDataProduct.java
Labels: lgtm, size/XL, cla: yes

#119 Update dependencies
  components/ord-service/pom.xml
Labels: :wave: request review, size/XS, lgtm, cla: yes

#121 Update base image
  components/ord-service/Dockerfile
Labels: size/XS, lgtm, cla: yes

#120 Add lastUpdate property to Consumption Bundle Entity
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/BundleEntity.java
Labels: size/XS, lgtm, cla: yes
