Repository kyma-incubator/ord-service, pull requests merged in 2024-02, with the labels that each got.

#122 SpringBoot Update
  components/ord-service/pom.xml
Labels: size/XS, lgtm, cla: yes

#124 Expose information about the formation type, formation and formation assignment
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/FormationDetails.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/storage/model/SystemInstanceEntity.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/Token.java
Labels: size/M, lgtm, cla: yes

#126 Add deprecation notice
  README.md
Labels: size/XS, lgtm, cla: yes

#125 Extend application tenant check
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/controller/ODataController.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/repository/SelfRegisteredRepository.java
  components/ord-service/src/main/java/com/sap/cloud/cmp/ord/service/token/Token.java
Labels: size/S, lgtm, cla: yes
